### Product APIS

### Get products
GET http://localhost:8000/api/v1/product/sony-tv

//title":"",status, price, quantity, description,sale price, saleStartDate,saleEndDate,brand, categories
//slug, image
### create a new product
POST http://localhost:8000/api/v1/product
Content-Type: application/json

{
   "status": true,
 "title": "apple ipad",
 "price": 500,
 "qty": 50,
 "description": "Awesome tab",
 "categories": "electronics",
 "salePrice": 0,
 "saleStartDate": "",
 "saleEndDate": "", 
 "brand": "apple"
}


### delete a new product
DELETE http://localhost:8000/api/v1/product/6165fcbd929e07ff2b4aa8bf
Content-Type: application/json