# user api lists

###  post
PUT http://localhost:8000/api/v1/user
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvbjRnQGFhLmNvbSIsImlhdCI6MTYzMzkwNDMyOSwiZXhwIjoxNjMzOTA1MjI5fQ.1Fi563SnI1o-_R_-vk9swM0qkUs73SkLU_KtY8C8qtw

{
    "fname":"Luit",
    "lname": "Saikia",
    "phone":"222222",
    "dob": "1993-04-23",
    "address":"11 11 11",
    "gender":"male"
}
###  create user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname":"Luit2n",
    "lname": "Saikia",
    "email":"bon4g@aa.com",
    "password":"3hhss3",
    "phone":"222222",
    "dob": "1993-04-23",
    "address":"11 11 11",
    "gender":"male"
    


}

###  email verification
POST http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    
    "email":"bon4g@aa.com",
    "otp": "23343"
    
}




###  get
GET http://localhost:8000/api/v1/user
Content-Type: application/json


###### Login Api

### admin Login
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email":"bon4g@aa.com",
    "password": "3hhss3"
}
### update password
PATCH http://localhost:8000/api/v1/user/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvbjRnQGFhLmNvbSIsImlhdCI6MTYzMzkxMjQzOCwiZXhwIjoxNjMzOTEzMzM4fQ.FRBhdqvWhnryd0IWpS0Lxx2LZBlTJeARtG31_W4Mukc

{
    "currentPassword": "3hhss3",
    "password":"1234Aa/"
}



########### Category APIS

### create category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
"name": "garden-ware",
"parentCat": null
}
### update category
PATCH http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "_id":"615284ef9d9bdd387d1e9e3f",
"name": "Poultry",
"parentCat": "61524a398dfe26ef39a8b028"
}


### fetch category
GET http://localhost:8000/api/v1/category
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvbjRnQGFhLmNvbSIsImlhdCI6MTYzMzQwMTkwNSwiZXhwIjoxNjMzNDAyODA1fQ.izUUDl926ET7pV0UlW9llYd1rrOF0axuTrhdNp_r3-Ia
### delete category
DELETE http://localhost:8000/api/v1/category/61510716fa1a8a86328bada8


##########t   token API
### request for a new refreshJWT
GET http://localhost:8000/api/v1/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvbjRnQGFhLmNvbSIsImlhdCI6MTYzMzM4NDk5MywiZXhwIjoxNjM1OTc2OTkzfQ.k5f7TYPuP3SgPBSJazEGv_-iZarozM04esTNkEgbZ5o