# user api lists

###  post
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname":"Luit2n",
    "lname": "Saikia",
    "email":"bon4g@aa.com",
    "password":"3hhss3",
    "phone":"222222",
    "dob": "1993-04-23",
    "address":"11 11 11",
    "gender":"male"
    


}

###  email verification
POST http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    
    "email":"bon4g@aa.com",
    "otp": "23343"
    
}




###  get
GET http://localhost:8000/api/v1/user
Content-Type: application/json

